-- Cleanup: remove fictional multi-brand catalog seed data.
-- DSOM is a mono-brand. The fake brands and placeholder products were
-- generated by Lovable AI during prototyping and are misleading
-- for real visitors. This migration removes them so only DSOM
-- products and the DSOM brand entry remain.

-- ── Hide and delete fake brands ─────────────────────────────────────
-- We use name-based matching (case-insensitive) so this is safe to
-- re-run even if rows were already cleaned manually.

UPDATE brands
SET is_visible = false
WHERE LOWER(name) IN ('maison lumière', 'maison lumiere', 'aurelia botanique');

-- Detach any products still referencing those brands before delete
UPDATE products
SET brand_id = NULL
WHERE brand_id IN (
  SELECT id FROM brands
  WHERE LOWER(name) IN ('maison lumière', 'maison lumiere', 'aurelia botanique')
);

DELETE FROM brands
WHERE LOWER(name) IN ('maison lumière', 'maison lumiere', 'aurelia botanique');

-- ── Hide and delete placeholder products ─────────────────────────────
-- These French-named items were generated as catalog filler and don't
-- correspond to any real DSOM SKU.

UPDATE products
SET is_visible = false
WHERE LOWER(name) IN (
  'sérum lumière', 'serum lumiere',
  'crème velours', 'creme velours',
  'huile précieuse', 'huile precieuse',
  'eau florale',
  'lait corps',
  'masque éclat', 'masque eclat',
  'mousse pure',
  'mousse douce',
  'voile solaire spf 50', 'voile solaire',
  'regard précis', 'regard precis'
);

DELETE FROM products
WHERE LOWER(name) IN (
  'sérum lumière', 'serum lumiere',
  'crème velours', 'creme velours',
  'huile précieuse', 'huile precieuse',
  'eau florale',
  'lait corps',
  'masque éclat', 'masque eclat',
  'mousse pure',
  'mousse douce',
  'voile solaire spf 50', 'voile solaire',
  'regard précis', 'regard precis'
);
